[new requirement: red]:handle empty name
when our function is called with an empty string it defaults to printing "Hello, World", rather than "Hello, ".

--- FAIL: TestHello (0.00s)
    --- FAIL: TestHello/say_'Hello,_world'_when_an_empty_string_is_supplied_ (0.00s)
        hello_test.go:25: got "Hello, " want "Hello, world"
FAIL
exit status 1
FAIL    github.com/huan11/learn-go-by-tdd       0.324s